# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/" target="_blank">@</a>.'
url:              http://hyde.getpoole.com
baseurl:          /



author:
  name:           'Gokulvasan'
  url:            https://twitter.com/

paginate:    10
paginate_path: "/blog/page:num/"

menu:
  - text: Portfolio
    link: /
    icon: ""

#  - text: Skills & Offers
 #   link: /skills-and-offers
  #  icon: ""
#
 # - text: Contact Me
  #  link: /contact
   # icon: ""

  #- text: My Resume
   # link: /resume
    #icon: ""

 # - text: Blog Posts
  #  link: /blog
   # icon: ""

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
