# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
#permalink:        pretty
#relative_permalinks: true




# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/" target="_blank">@</a>.'
url:              https://ajay6023.github.io
baseurl:          '/gokulvasan'



author:
  name:           'Gokulvasan'
  url:            https://twitter.com/

paginate:    10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
